### ISSUE TITLE
请问怎样获取好友的用户名？

### ISSUE THREAD

**Issue by btfak** [songtianyi/wechat-go#1]
比如我有个好友用户名是yanyuanvip，但Message报文中的原文是：
```
UserName: @1ce4dc3864239ea574adfde537dc50a0
```

你知道怎样获取原始的用户名吗？

**Comment by songtianyi** [comment]
@btfak 无法获取到真实id，wechat的接口给的是动态id。
有一个解决方法是自己加备注（自定义id）
