### ISSUE TITLE
运行了一下，还是不明白项目解决的问题是什么？

### ISSUE THREAD

**Issue by anbaoyong** [songtianyi/wechat-go#11]
如题：项目下载下来运行正常扫码网页登录，然后就看到命令行一堆日志，没搞懂我能用它来做什么？想请教一下作者，谢谢！！

**Comment by songtianyi** [comment]
在聊天窗口输入
```
美女
```
有惊喜。
可参考README中的插件列表，了解下怎么使用和控制插件。

**Comment by anbaoyong** [comment]
跟谁之间的对话框？

**Comment by songtianyi** [comment]
@anbaoyong 
....anyone

**Comment by anbaoyong** [comment]
我知道为什么不行了，是因为那些插件都是disable，文档看的不仔细，多谢
