### ISSUE TITLE
接受到群消息时，如果发消息人不是我的好友，取不到群里发消息人的昵称

### ISSUE THREAD

**Issue by luochaolun** [songtianyi/wechat-go#13]
接受到群消息时，如果发消息人不是我的好友，取不到群里发消息人的昵称。

接受到群消息时，logs.Info(“%+v”, msg) 

好几个信息为nil

        mm, err := wxweb.CreateMemberManagerFromGroupContact(session, contact)
	if err != nil {
		logs.Debug(err)
		return
	}
	who := mm.GetContactByUserName(msg.Who)

发消息的人和我是好友，who里有内容，不是好友，who为nil

**Comment by songtianyi** [comment]
@luochaolun 
可能有bug，我看下。

**Comment by songtianyi** [comment]
@luochaolun 
没有重现呀。

**Comment by songtianyi** [comment]
@luochaolun 
把详细的关键信息打印出来，
contact
mm.Group.NickName
mm.Group.MemberList

**Comment by luochaolun** [comment]
contact是nil

加下qq吧，46445280

**Comment by songtianyi** [comment]
@luochaolun 
获取contact的代码？

**Comment by songtianyi** [comment]
更新到最新的代码。
