### ISSUE TITLE
每次登陆都出现 [E] invalid response, window.code=201;

### ISSUE THREAD

**Issue by laike9m** [songtianyi/wechat-go#14]
```
2017/07/04 23:20:17 [E] invalid response, window.code=201;
...
2017/07/04 23:20:25 [I] entering synccheck loop
2017/07/04 23:20:25 [I] webpush.wx2.qq.com 0 2
2017/07/04 23:20:26 [E] handlers for key [51] not registered
```

**Comment by songtianyi** [comment]
@laike9m 
这个报错没有影响，登录进去之前有个扫码过程，扫码过程中会不断获取扫码状态，那个错误的意思是还未登录。我改下log级别。

**Comment by songtianyi** [comment]
@laike9m 
msg type为51的是特殊消息，目前没处理，所以每次来这类消息都有报错。

**Comment by laike9m** [comment]
谢谢。我还有个问题：[示例代码](https://github.com/songtianyi/wechat-go#基于wechat-go创建自定义的机器人)里面，如果想打出接到的每一条消息，应该怎么做呢？

**Comment by songtianyi** [comment]
什么情况下有这种需求呢，调试？
可以在 wxweb/session.go 中的consumer函数里打印收到的json，也可以打印解析后的消息 rmsg。

**Comment by laike9m** [comment]
thanks。其实没什么特定需求，我昨天才看到这个库，试了下demo还没看代码，所以问问

2017年7月5日 上午10:54，"songtianyi" <notifications@github.com>写道：

**Comment by songtianyi** [comment]
ok
@laike9m
