### ISSUE TITLE
可以和php交互吗?

### ISSUE THREAD

**Issue by ifour333** [songtianyi/wechat-go#18]
比如go语言只服务于监控消息的收发，长轮训接受消息
类似于 https://github.com/sjdy521/Mojo-Weixin
这样的 因为mojo可能不是多线程的而且不稳定
不知道你这个go版本的 是不是能 做成mojo这样的

**Comment by songtianyi** [comment]
wechat-go本身是一个golang包 只能被go程序调用。 想要和其它语言交互 ，需要自己用go包一层网络服务出来比如 go-aida的web页面 就是调用的 go包装出来的API
