### ISSUE TITLE
获取订阅好或者公众号,消息类型为49提示  [W] no handlers for key [49]

### ISSUE THREAD

**Issue by owengaozhen** [songtianyi/wechat-go#25]
session.HandlerRegister.Add(wxweb.MSG_LINK, wxweb.Handler(demo), "textdemo")

func demo(session *wxweb.Session, msg *wxweb.ReceivedMessage) {
	fmt.Println(fmt.Sprintf("%v", msg.Content))
	fmt.Println(fmt.Sprintf("%#v", msg))
}

**Comment by songtianyi** [comment]
还有问题不？

**Comment by owengaozhen** [comment]
可以的..没有问题
