### ISSUE TITLE
*[E] session exit, json: cannot unmarshal number 2147586143 into Go value of type int**

### ISSUE THREAD

**Issue by lamproae** [songtianyi/wechat-go#3]
[pi@raspberrypi ~/c/wechat-go/tests] $ uname -a 
Linux raspberrypi 4.4.21-v7+ #911 SMP Thu Sep 15 14:22:38 BST 2016 armv7l GNU/Linux
[pi@raspberrypi ~/c/wechat-go/tests] $ 
[pi@raspberrypi ~/c/wechat-go/tests] $ go version
go version go1.7.3 linux/arm
[pi@raspberrypi ~/c/wechat-go/tests] $ 

~                                                                                                                                                            
[pi@raspberrypi ~/c/wechat-go/tests] $ go run test.go         
2017/04/28 12:41:53 [D] AfPX6FT9Gw==
                                                
                                                              
2017/04/28 12:41:57 [E] invalid response, window.code=201;
2017/04/28 12:42:09 [D] &{2147483647 @403654952e7d01e4edbcf418f042774c cp4 /cgi-bin/mmwebwx-bin/webwxgeticon?seq=541739479&username=@403654952e7d01e4edbcf418f042774c&skey=@crypt_b31d43c3_df0d7355e9ba022aaf84cff4bc66db3c 0 0 []      0 0 1 become an old man, filled with regret, waiting to die alone 0 0 0    0 0 2 1 17 0  0   0 0}
2017/04/28 12:42:13 **[E] session exit, json: cannot unmarshal number 2147586143 into Go value of type int**

**Comment by songtianyi** [comment]
多少位的arm？
代码修改过？请提供运行代码。
你的arm我可以登陆不？

**Comment by songtianyi** [comment]
@lamproae 
我找来了树莓派设备，麻烦提供下安装的系统和版本
https://www.raspberrypi.org/downloads/

**Comment by lamproae** [comment]
我装的官方的版本

**Comment by lamproae** [comment]
硬件是3b,上次试了一次以后就没用了，晚上再试下吧

**Comment by songtianyi** [comment]
fixed!
