### ISSUE TITLE
Using terminal_bot

### ISSUE THREAD

**Issue by suntong** [songtianyi/wechat-go#35]
Same as issues#11, I did:

```
go build examples/linux/terminal_bot.go
./terminal_bot
```

运行正常扫码网页登录，然后就看到命令行一堆日志

```
2017/11/22 06:51:20 [I] entering synccheck loop
2017/11/22 06:51:50 [I] webpush.web.wechat.com 0 0
2017/11/22 06:51:50 [E] Get https://webpush.web.wechat.com/cgi-bin/mmwebwx-bin/synccheck?_=1511351480000&deviceid=e020835203446392&r=1511351480000&sid=99FIil9hg4bBx3oe&skey=%40crypt_73c0b781_67708c6d636e654a635ad9cc2b305a50&synckey=1_667580454%7C2_667580845%7C3_667580399%7C1000_1511345522&uin=2849091348: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
2017/11/22 06:52:20 [I] webpush.web.wechat.com 0 0
2017/11/22 06:52:20 [E] Get https://webpush.web.wechat.com/cgi-bin/mmwebwx-bin/synccheck?_=1511351510000&deviceid=e020835203446392&r=1511351510000&sid=99FIil9hg4bBx3oe&skey=%40crypt_73c0b781_67708c6d636e654a635ad9cc2b305a50&synckey=1_667580454%7C2_667580845%7C3_667580399%7C1000_1511345522&uin=2849091348: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
2017/11/22 06:52:50 [I] webpush.web.wechat.com 0 0
```

没搞懂 how to verify that it is working fine. 

我在聊天窗口输入

美女

but nothing happened. 

same for "`笑话`". 

How to verify that it is working fine? Thx.

**Comment by suntong** [comment]
> 因为那些插件都是disable

Is it this line
https://github.com/songtianyi/wechat-go/blob/master/examples/linux/terminal_bot.go#L45

Then how can I enable them?

**Comment by suntong** [comment]
I've commented the whole block out but I'm still not getting anything. 

please help. Thx.

**Comment by suntong** [comment]
commented the whole block out works. 

It just took some time to get back ...

**Comment by songtianyi** [comment]
plugins would be enabled by default.
It works fine for me, you can try more wechat accounts to locate the reason. Maybe your account was blocked by Tencent for some reason.

**Comment by suntong** [comment]
Got it. Thanks @songtianyi.
