### ISSUE TITLE
add to switcher the 管理插件的插件

### ISSUE THREAD

**Issue by suntong** [songtianyi/wechat-go#36]
Hi @songtianyi,

The new plugin that I'm writting (https://github.com/songtianyi/wechat-go/issues/34) need more functionalities to `switcher` the 管理插件的插件. So far it supports:

> #关闭某个插件, 在微信聊天窗口输入
disable faceplusplus
#开启某个插件, 在微信聊天窗口输入
enable faceplusplus
#查看所有插件信息, 在微信聊天窗口输入
dump

Please (consider)  adding one more command to it, 

**config** [plugin] more config strings for the plugin

and have a way for the plugin to take the `more config strings for the plugin` and do its own configuration. 

I need to pass two integers to my plugin for its configuration, which I can take care of it myself when I get the string. 

Thanks for consideration!

**Comment by songtianyi** [comment]
```
session.HandlerRegister.GetByName(`string`).SetConfig(`string`,  `interface{}`)
```
```
session.HandlerRegister.GetByName(`string`).GetConfig(`string`) `interface{}`
```
It's that ok for you?

**Comment by songtianyi** [comment]
I prefer to add a local(or remote) memory config store to manage user configurations, and add a new plugin to do getter or setter things.

**Comment by suntong** [comment]
I trust you'd make the best decision, so whatever you decide and implement, I'll use it. 

Thanks for doing that.

**Comment by songtianyi** [comment]
Sorry, i'll implement the feature this weekend.

**Comment by songtianyi** [comment]
Done. Please check the latest commit.

**Comment by suntong** [comment]
Cool!

I'll take a look this weekend -- I was recovering from the jet-lag after a short trip to China...
