### ISSUE TITLE
新号，已实名，无法登录

### ISSUE THREAD

**Issue by nifflerfox** [songtianyi/wechat-go#67]
返回如下：

`<error><ret>1203</ret><message>为了你的帐号安全，此微信号已不允许登录网页微信。你可以使用Windows微信或Mac微信在电脑端登录。Windows微信下载地址：https://pc.weixin.qq.com  Mac微信下载地址：https://mac.weixin.qq.com</message></error>`

有解决办法吗？谢谢！

**Comment by songtianyi** [comment]
信号已经不能使用网页端，没有办法。

**Comment by qq562641869** [comment]
2019已经没法玩了？

**Comment by songtianyi** [comment]
新号应该被禁了
