### ISSUE TITLE
timeout for webwxsync, synccheck

### ISSUE THREAD

**Issue by qighliu29** [songtianyi/wechat-go#8]
不设置timeout 发送自定义表情 webwxsync/synccheck 会hang up
https://github.com/HalfdogStudio/wechat-user-bot/issues/35

**Comment by songtianyi** [comment]
@qighliu29 
提醒下复现代码

**Comment by qighliu29** [comment]
2017/06/02 14:18:21 [I] entering synccheck loop
2017/06/02 14:18:21 [I] webpush.wx2.qq.com 0 2
2017/06/02 14:18:21 [E] handlers for key [51] not registered
2017/06/02 14:18:21 [E] handlers for key [51] not registered
2017/06/02 14:18:27 [I] webpush.wx2.qq.com 0 2
2017/06/02 14:18:27 [E] handlers for key [47] not registered
2017/06/02 14:18:27 [I] webpush.wx2.qq.com 0 2
2017/06/02 14:18:27 [I] webpush.wx2.qq.com 0 2
2017/06/02 14:18:28 [I] webpush.wx2.qq.com 0 2
2017/06/02 14:18:28 [I] webpush.wx2.qq.com 0 2
2017/06/02 14:18:28 [I] webpush.wx2.qq.com 0 2
2017/06/02 14:18:28 [I] webpush.wx2.qq.com 0 2
2017/06/02 14:18:28 [I] webpush.wx2.qq.com 0 2
2017/06/02 14:18:29 [I] webpush.wx2.qq.com 0 2
2017/06/02 14:18:29 [I] webpush.wx2.qq.com 0 2
2017/06/02 14:18:29 [I] webpush.wx2.qq.com 0 2
2017/06/02 14:18:29 [I] webpush.wx2.qq.com 0 2
2017/06/02 14:18:29 [I] webpush.wx2.qq.com 0 2
2017/06/02 14:18:30 [I] webpush.wx2.qq.com 0 2

日志到这里就hang住了, 有时候"webpush.wx2.qq.com 0 2"更多才hang住, 我是 win x64
在WebWxSync和SyncCheck里加log发现`resp, err := client.Do(req)`没有出来
表情 我尝试自定义的都能触发hang up, 商店的没试

**Comment by qighliu29** [comment]
试了gifer插件, 一个账号可以, 一个账号在
SendEmotionFromBytes的WebWxUploadMedia返回BaseResponse.Ret=1100
是被判定为机器人了吗?
有什么规避方法?

**Comment by songtianyi** [comment]
@qighliu29
是在非Windows下编译的还是windows下？

**Comment by qighliu29** [comment]
上面的是在windows下编译的
手头没windows机器了, 在mac上分别编译TERMINAL_MODE和WEB_MODE, 都可以复现hang up
webpush.wx2.qq.com 0 2 消息多了很多
之前忘了说, 都是自己发给自己

**Comment by qighliu29** [comment]
又试了一下 没有再出现发一个表情卡死的现象, 也不会出现很多webpush.wx2.qq.com 0 2了
但连续发多个表情给bot, 还是会卡住, 应该是web微信的频率限制
因此还是建议client.Do那里加上超时

**Comment by songtianyi** [comment]
@qighliu29 
0 2 代表syncheck检测到了消息，文件大的时候会比较多，晚上把超时加上。

**Comment by qighliu29** [comment]
webwxsync加timeout没有问题
但是web微信好像总有一个synccheck在pending, 不知道是什么逻辑

**Comment by songtianyi** [comment]
@qighliu29 
如果没有消息会过很久才回。你说的hang住应该是在syncheck里吧？

**Comment by qighliu29** [comment]
hang up先是在webwxsync里
webwxsync加了超时之后发现syncheck有时候也会hang住, 这种不是正常的pending, 再发文本消息/退出也不会出来
可以先只处理webwxsync, 剩下的不管

**Comment by qighliu29** [comment]
> hang up先是在webwxsync里
webwxsync加了超时之后发现syncheck有时候也会hang住, 这种不是正常的pending, 再发文本消息/退出也不会出来
可以先只处理webwxsync, 剩下的不管

或者给syncheck设置稍大的timeout, 我自己试了试没发现什么副作用 (除了会很多timeout log)

**Comment by jackXJ** [comment]
Hi
在mac上跑了下，出现二维码，但是手机扫码没反应。

2017/06/06 00:34:27 [E] session exit, invalid response, window.code=408;
2017/06/06 00:34:27 [I] trying re-login with cache
2017/06/06 00:34:27 [E] re-login error, Post /webwxinit?pass_ticket=&r=1496734467&skey=: unsupported protocol scheme ""
2017/06/06 00:34:30 [I] trying re-login with cache
2017/06/06 00:34:30 [E] re-login error, Post /webwxinit?pass_ticket=&r=1496734470&skey=: unsupported protocol scheme ""
2017/06/06 00:34:33 [I] trying re-login with cache
2017/06/06 00:34:33 [E] re-login error, Post /webwxinit?pass_ticket=&r=1496734473&skey=: unsupported protocol scheme ""

这是日志。

**Comment by songtianyi** [comment]
@jackXJ 
过了多久扫描的？408表示过期了，可以等它刷新。
btw 新问题可以新开issue。

**Comment by songtianyi** [comment]
@qighliu29 
你可以提交一个pr

**Comment by qighliu29** [comment]
这个算完结了吧

**Comment by songtianyi** [comment]
@qighliu29 
嗯，🙏
