### ISSUE TITLE
不能获取群组信息

### ISSUE THREAD

**Issue by superlonger** [songtianyi/wechat-go#9]
songtianyi,
你好，我正在学习你的代码。我测试时发现，在forwarder.go文件中，
执行下列步骤时，一直出错
`var contact *wxweb.User
	if msg.FromUserName == session.Bot.UserName {
		contact = session.Cm.GetContactByUserName(msg.ToUserName)
	} else {
		contact = session.Cm.GetContactByUserName(msg.FromUserName)
	}
	if contact == nil {
		return
	}`
这里的contact始终为nil，而这时的contactUserName即是以@@开头的群组的username，不知道大家没有遇到过这个问题。

**Comment by songtianyi** [comment]
@superlonger 
将需要的群组保存到通讯录，这是为了避免骚扰。

**Comment by superlonger** [comment]
我晕，大神，我研究了半天，才刚刚试出来，也是这个结果。需要将群组保存到通讯录，才能正常获取。
要是我早3个小时来看一下回复就好了。
多谢了。   ^_^

**Comment by songtianyi** [comment]
@superlonger
抱歉，我在示例代码里加个注释。
