### ISSUE TITLE
微控BUG反馈帖

### ISSUE THREAD

**Issue by LiChangXing** [songtianyi/wechat-go#93]
大家有问题可以在此帖问，每日有研发回复~

**Comment by iyjian** [comment]
获取朋友圈返回数据为空，但实际上此微信账号下有朋友圈。

[2020-03-06T11:02:38.857] [DEBUG] api - request:  {"url":"/getCircle","method":"post","data":{"wId":"00000170-99c5-641e-0000-e811f4092976","statusId":0}}
[2020-03-06T11:02:38.961] [DEBUG] api - response:  {"message":"成功","code":"1000","data":null}

**Comment by iyjian** [comment]
获取群二维码失败：

client_1_b017e0743dad | [2020-03-06T11:11:34.990] [ERROR] api - request "{\"wId\":\"00000170-ad9c-9c7f-0000-53663e1d03d6\",\"wcId\":\"6602798965@chatroom\"}"
client_1_b017e0743dad | [2020-03-06T11:11:34.990] [ERROR] api - response:  {"message":"失败","code":"1001","data":null}

**Comment by LiChangXing** [comment]
> 获取群二维码失败：
> 
> client_1_b017e0743dad | [2020-03-06T11:11:34.990] [ERROR] api - request "{"wId":"00000170-ad9c-9c7f-0000-53663e1d03d6","wcId":"6602798965@chatroom"}"
> client_1_b017e0743dad | [2020-03-06T11:11:34.990] [ERROR] api - response: {"message":"失败","code":"1001","data":null}

群号不是你所属微信下的，你弄混淆了。
